# title: VentureSeed
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/Logo.png"

description: AI-Powered Scenario-Based Entrepreneurship Practice Platform
theme: just-the-docs

url: https://CoolSoda11.github.io/VentureSeed
# aux_links:
  # Template Repository: https://github.com/CoolSoda11/VentureSeed
